#ifndef DEFINES_H
#define DEFINES_H

// LOG OPTIONS - DESCOMENTAR LO QUE QUERES LOGUEAR
//#define DBG_SENDPACKETDATA
//#define DBG_BLOCKPKT

//ID de funciones y comandos del server
enum Functions
{
    CODE_NOP,
    CODE_SEND,
    CODE_SENDTO,
    CODE_RECV,
    CODE_RECVFROM,
    CODE_WS2SEND,
    CODE_WS2SENDTO,
    CODE_WS2RECV,
    CODE_WS2RECVFROM,
    CODE_WSASEND,
    CODE_WSASENDTO,
    CODE_WSARECV,
    CODE_WSARECVFROM,
    CODE_PR_SEND,
    CODE_PR_RECV,
    CODE_PR_READ,
    CODE_PR_WRITE,
    CODE_SSLENCRYPTPACKET,
    CODE_SSLDECRYPTPACKET,
    CODE_ENCRYPTMESSAGE,
    CODE_DECRYPTMESSAGE,
    CODE_SSL_READ,
    CODE_SSL_WRITE
};

enum ServerCodes
{
    SCODE_NOP,
    SCODE_INJECTPACKET,
    SCODE_SETPACKET,
    SCODE_STARTFILTERING,
    SCODE_STOPFILTERING,
    SCODE_STARTCAPTURE,
    SCODE_STOPCAPTURE,
    SCODE_LOADDLLEX,
    SCODE_UNLOADDLLEX,
};

typedef struct
{
    Functions functionId;
    UINT16 socketId;
    UINT32 localIp;
    UINT32 remoteIp;
    UINT16 localPort;
    UINT16 remotePort;
    UINT16 size;
} PacketInfo;



#endif // DEFINES_H
